import { ParcelInput } from "@/types";

export const SAMPLE_SCENARIOS: { label: string; description: string; data: ParcelInput }[] = [
  {
    label: "Belediye İhalesi: Çanakkale Kepez Konut Arsası",
    description: "İhale Başlangıç: 14.500.000 TL — Emsal 1.50 — 24 Dairelik Proje Potansiyeli",
    data: {
      category: "arsa",
      title: "Çanakkale Kepez Sahil Bölgesi Konut Geliştirme Parseli",
      city: "Çanakkale",
      district: "Merkez",
      neighborhood: "Kepez",
      ada: "248",
      parsel: "12",
      areaM2: 1650,
      roadAccess: "var",
      roadFrontageM: 28,
      isCornerParcel: true,
      topography: "duz",
      zoningType: "konut",
      kaks: 1.50,
      taks: 0.35,
      gabariM: 15.5,
      maxFloors: 5,
      relinquishmentRatio: 10,
      askedPriceTL: 14500000,
      isTender: true,
      tenderAuthority: "Çanakkale Belediyesi İhale Birimi",
      tenderFileNo: "2026/04-İH-17",
      estimatedLandM2PriceTL: 13000,
      estimatedUnitSaleM2PriceTL: 45000,
      contractorSharePercent: 50,
      consultantName: "Hasan Hüseyin Yıldırım",
      consultantPhone: "0850 840 86 95",
      consultantAgency: "İhaleciBurada Kurumsal Portföy",
      notes: "Deniz manzaralı, ana artere 150m mesafede. Belediye mülkiyetinden açık artırma ile satış.",
    }
  },
  {
    label: "İcra İhalesi: Kadıköy Moda 3+1 Daire",
    description: "İhale Başlangıç: 9.800.000 TL — 135 m² — 55.000 TL Aylık Kira Getirisi",
    data: {
      category: "konut",
      title: "Kadıköy Moda Sahil Yakını 3+1 Geniş Ara Kat Daire",
      city: "İstanbul",
      district: "Kadıköy",
      neighborhood: "Caferağa",
      ada: "184",
      parsel: "22",
      areaM2: 135,
      netAreaM2: 115,
      housingType: "daire",
      roomCount: "3+1",
      buildingAge: "1-5",
      floorLocation: "ara_kat",
      totalFloorsInBuilding: 5,
      heatingType: "dogalgaz_kombi",
      deedStatus: "kat_mulkiyeti",
      hasElevator: true,
      hasParking: true,
      hasBalcony: true,
      inGatedCommunity: false,
      isFurnished: false,
      isCreditEligible: true,
      monthlyRentEstimateTL: 55000,
      roadAccess: "var",
      roadFrontageM: 15,
      isCornerParcel: false,
      topography: "duz",
      zoningType: "konut",
      kaks: 1.5,
      taks: 0.35,
      gabariM: 15,
      maxFloors: 5,
      relinquishmentRatio: 0,
      askedPriceTL: 9800000,
      isTender: true,
      tenderAuthority: "İstanbul Anadolu 4. İcra Dairesi",
      tenderFileNo: "2026/842-ESAT",
      estimatedLandM2PriceTL: 36000,
      estimatedUnitSaleM2PriceTL: 95000,
      contractorSharePercent: 50,
      consultantName: "Hasan Hüseyin Yıldırım",
      consultantPhone: "0850 840 86 95",
      consultantAgency: "İhaleciBurada Gayrimenkul İcra Masası",
      notes: "Metro ve tramvay durağına 300 metre mesafede, yüksek kira çarpanlı birinci sınıf lokasyon.",
    }
  },
  {
    label: "Satılık Müstakil Villa: Muğla Bodrum Yalıkavak",
    description: "Özel Havuzlu 4+1 Müstakil Villa — 280 m² Brüt — Yüksek Prim Potansiyeli",
    data: {
      category: "konut",
      title: "Bodrum Yalıkavak Marina Manzaralı Müstakil Havuzlu Villa",
      city: "Muğla",
      district: "Bodrum",
      neighborhood: "Yalıkavak",
      ada: "512",
      parsel: "4",
      areaM2: 280,
      netAreaM2: 240,
      housingType: "villa",
      roomCount: "4+1",
      buildingAge: "0",
      floorLocation: "mustakil",
      totalFloorsInBuilding: 2,
      heatingType: "yerden_isitma",
      deedStatus: "kat_mulkiyeti",
      hasElevator: false,
      hasParking: true,
      hasBalcony: true,
      inGatedCommunity: true,
      isFurnished: true,
      isCreditEligible: true,
      monthlyRentEstimateTL: 140000,
      roadAccess: "var",
      roadFrontageM: 25,
      isCornerParcel: true,
      topography: "az_egimli",
      zoningType: "villa",
      kaks: 0.6,
      taks: 0.2,
      gabariM: 6.5,
      maxFloors: 2,
      relinquishmentRatio: 0,
      askedPriceTL: 34500000,
      isTender: false,
      estimatedLandM2PriceTL: 31000,
      estimatedUnitSaleM2PriceTL: 130000,
      contractorSharePercent: 45,
      consultantName: "Selim Çetin",
      consultantPhone: "0532 999 88 77",
      consultantAgency: "Bodrum Elite Portföy",
      notes: "Yalıkavak Marina'ya 5 dakika sürüş mesafesinde, akıllı ev sistemli, müstakil bahçe ve sonsuzluk havuzlu.",
    }
  },
  {
    label: "Kat Karşılığı: İstanbul Çekmeköy Villa / Konut",
    description: "Emlakçı Portföyü: 2.400 m² — Emsal 0.80 — Butik Site Yapımına Uygun",
    data: {
      category: "arsa",
      title: "Çekmeköy Orman Kenarı Butik Konut & Villa Arsası",
      city: "İstanbul",
      district: "Çekmeköy",
      neighborhood: "Ömerli",
      ada: "1420",
      parsel: "3",
      areaM2: 2400,
      roadAccess: "var",
      roadFrontageM: 35,
      isCornerParcel: false,
      topography: "az_egimli",
      zoningType: "villa",
      kaks: 0.80,
      taks: 0.25,
      gabariM: 9.5,
      maxFloors: 3,
      relinquishmentRatio: 15,
      askedPriceTL: 32000000,
      isTender: false,
      estimatedLandM2PriceTL: 15000,
      estimatedUnitSaleM2PriceTL: 68000,
      contractorSharePercent: 48,
      consultantName: "Ahmet Erdem",
      consultantPhone: "0532 555 12 34",
      consultantAgency: "Ömerli Gayrimenkul Yatırım Danışmanlığı",
      notes: "Doğa ile iç içe, müstakil girişli 12 adet ikiz villa yapımına imkan tanıyan temiz kadastro parseli.",
    }
  }
];

export function formatTL(amount: number): string {
  if (isNaN(amount)) return "0 ₺";
  return new Intl.NumberFormat("tr-TR", {
    style: "currency",
    currency: "TRY",
    maximumFractionDigits: 0,
  }).format(amount).replace("TRY", "₺");
}

export function formatNumber(amount: number): string {
  if (isNaN(amount)) return "0";
  return new Intl.NumberFormat("tr-TR", {
    maximumFractionDigits: 1,
  }).format(amount);
}
